import{db}from'../../../core/db/index.js';import{nutritionStore}from'../store/index.js';import{pantryService}from'./pantry.service.js';import{bus}from'../../../core/bus/index.js';import{i18nService}from'../../../core/i18n/i18n.service.js';const VAULT_NAME='nutrition_vault';const MAX_MEALS=10;class JournalService{constructor(){this.isReady=false;}
async init(){if(this.isReady)return true;console.log('[JOURNAL] Abriendo los libros de cuentas...');try{const allDocs=await db.getAll(VAULT_NAME);const mealPlans=allDocs.filter(doc=>doc.id.startsWith('plan_meal_')&&doc.isVisible);mealPlans.sort((a,b)=>(a.order||0)-(b.order||0));const activePlanIds=mealPlans.map(plan=>plan.id);if(activePlanIds.length===0){console.log('[JOURNAL] Creando plantillas por defecto...');this.dict=await i18nService.loadPage('nutrition_core/journal');await this.saveMealPlan('plan_meal_0',0,this.dict.t('default_meal_0'),'08:00');await this.saveMealPlan('plan_meal_1',1,this.dict.t('default_meal_1'),'14:30');await this.saveMealPlan('plan_meal_2',2,this.dict.t('default_meal_2'),'20:30');activePlanIds.push('plan_meal_0','plan_meal_1','plan_meal_2');}
nutritionStore.setMealPlanIds(activePlanIds);this.isReady=true;console.log(`[JOURNAL] Cuentas listas. ${activePlanIds.length} comidas configuradas.`);return true;}catch(error){console.error('[JOURNAL] Error leyendo las cuentas:',error);return false;}}
async getMealPlan(planId){return await db.get(VAULT_NAME,planId);}
async saveMealPlan(id,order,label,time,notification=false,items=[],isVisible=true){const plan={id,order,isVisible,label,time,notification:notification,items};await db.put(VAULT_NAME,plan);console.log(`[JOURNAL] Plantilla guardada: ${id} -> ${label} (Notif: ${notification})`);if('serviceWorker'in navigator&&navigator.serviceWorker.controller){navigator.serviceWorker.controller.postMessage({type:'MEAL_NOTIFICATION_UPDATE',payload:{id:plan.id,label:plan.label,time:plan.time,notification:plan.notification}});console.log(`[JOURNAL] Walkie-Talkie: Utillero, actualiza la alarma de [${plan.label}]`);}else{console.warn('[JOURNAL] El Utillero no está en la banda (Service Worker no activo o en primer registro).');}
return plan;}
async getMealLog(dateObj,planId){const logKey=this._getLogKey(dateObj,planId);const log=await db.get(VAULT_NAME,logKey);return log||{id:logKey,date:this._formatDateString(dateObj),mealId:planId,timestamp:null,eatenItems:[],totals:{k:0,p:0,c:0,f:0}};}
async saveMealLog(dateObj,planId,selectedItems){const logKey=this._getLogKey(dateObj,planId);const eatenItems=[];const totals={k:0,p:0,c:0,f:0};for(const item of selectedItems){const foodData=pantryService.getFoodById(item.refId);if(!foodData)continue;const ratio=(item.grams||100)/100;const calculated={k:Math.round(foodData.k*ratio),p:Math.round(foodData.p*ratio),c:Math.round(foodData.c*ratio),f:Math.round(foodData.f*ratio)};eatenItems.push({refId:item.refId,grams:item.grams,calculated:calculated});totals.k+=calculated.k;totals.p+=calculated.p;totals.c+=calculated.c;totals.f+=calculated.f;}
const currentGoal=nutritionStore.getDietGoal();const goalSnapshot=currentGoal?{targetKcal:currentGoal.targetKcal,minKcal:currentGoal.minKcal,maxKcal:currentGoal.maxKcal}:null;const logEntry={id:logKey,date:this._formatDateString(dateObj),mealId:planId,timestamp:Date.now(),eatenItems:eatenItems,totals:totals,goalSnapshot:goalSnapshot};await db.put(VAULT_NAME,logEntry);console.log(`[JOURNAL] Registro guardado en piedra: ${logKey} (${totals.k} kcal)`);bus.emit('JOURNAL_UPDATED',{date:dateObj});return logEntry;}
async getDailyTotals(dateObj){const activePlanIds=nutritionStore.getMealPlanIds();const dayTotals={k:0,p:0,c:0,f:0};for(const planId of activePlanIds){const log=await this.getMealLog(dateObj,planId);if(log&&log.totals){dayTotals.k+=log.totals.k;dayTotals.p+=log.totals.p;dayTotals.c+=log.totals.c;dayTotals.f+=log.totals.f;}}
return dayTotals;}
_getLogKey(dateObj,planId){const dateStr=this._formatDateString(dateObj);return`log_${dateStr}_${planId}`;}
_formatDateString(dateObj){const d=String(dateObj.getDate()).padStart(2,'0');const m=String(dateObj.getMonth()+1).padStart(2,'0');const y=dateObj.getFullYear();return`${d}_${m}_${y}`;}}
export const journalService=new JournalService();