import{db}from'../../../core/db/index.js';import{nutritionStore}from'../store/index.js';import{i18nService}from'../../../core/i18n/i18n.service.js';const MASTER_FILE_PATH='/src/assets/data/master_foods.json';const VAULT_NAME='nutrition_vault';const USER_DATA_KEY='user_pantry_data';class PantryService{constructor(){this.isReady=false;this.dict=null;}
async init(){if(this.isReady)return true;console.log('[PANTRY] Abriendo el almacén...');try{const[masterData,userRecord,dict]=await Promise.all([this._loadMasterFoods(),db.get(VAULT_NAME,USER_DATA_KEY),i18nService.loadPage('nutrition_core/pantry')]);this.dict=dict;nutritionStore.setMasterFoods(masterData);if(userRecord){nutritionStore.setUserData(userRecord.data);}else{nutritionStore.setUserData({foods:[],deletedIds:[]});}
this.isReady=true;console.log(`[PANTRY] Listo. Maestro: ${masterData.length} | Usuario: ${userRecord?.data?.foods?.length || 0}`);return true;}catch(error){console.error('[PANTRY] Error crítico al inicializar:',error);return false;}}
searchFood(query,category=null){const allFoods=nutritionStore.getAllFoods();let results=category?allFoods.filter(f=>f.category===category):allFoods;if(!query||query.trim()===''){return results.slice(0,50);}
const normalizedQuery=this._normalizeText(query);const terms=normalizedQuery.split(' ');results=results.filter(item=>{const nameStr=this.getFoodName(item);const normName=this._normalizeText(nameStr);return terms.every(term=>normName.includes(term));});return results.slice(0,50);}
getFoodById(id){const allFoods=nutritionStore.getAllFoods();return allFoods.find(f=>f.id===id)||null;}
getFoodName(foodItem){const fallback=this.dict?this.dict.t('fallback_food_name'):"Desconocido";if(!foodItem||!foodItem.name)return fallback;if(typeof foodItem.name==='string')return foodItem.name;const translatedName=i18nService.tData(foodItem.name);return translatedName||fallback;}
async saveCustomFood(foodObject){if(!foodObject.id){const prefix=foodObject.type==='group'?'G_':'C_';foodObject.id=`${prefix}${Date.now()}`;}
nutritionStore.addOrUpdateUserFood(foodObject);await this._syncUserDataToDB();console.log(`[PANTRY] Alimento/Grupo guardado: ${foodObject.id}`);return foodObject;}
async deleteFood(id){nutritionStore.removeUserFood(id);await this._syncUserDataToDB();console.log(`[PANTRY] Alimento procesado para borrado: ${id}`);}
async fetchRemoteFood(barcode){if(!navigator.onLine){console.warn('[OFF] Sin internet. Abortando búsqueda.');return null;}
const API_URL=`https://world.openfoodfacts.org/api/v0/product/${barcode}.json`;const controller=new AbortController();const timeoutId=setTimeout(()=>controller.abort(),3000);try{console.log(`[OFF] Escaneando ${barcode}...`);const response=await fetch(API_URL,{signal:controller.signal,headers:{'User-Agent':'Aerko_App - WebVersion - aerko.app'}});clearTimeout(timeoutId);if(!response.ok)throw new Error('Error HTTP '+response.status);const data=await response.json();if(data.status!==1||!data.product){console.log('[OFF] Producto no encontrado.');return null;}
const p=data.product;const n=p.nutriments||{};const fallbackEs=this.dict?this.dict.t('off_imported_food_es'):"Alimento Importado";const fallbackEn=this.dict?this.dict.t('off_imported_food_en'):"Imported Food";const cleanFood={id:`C_OFF_${barcode}`,name:{es:p.product_name_es||p.product_name||fallbackEs,en:p.product_name_en||p.product_name||fallbackEn},category:"Created",type:"Aliment",k:Math.round(Number(n['energy-kcal_100g']||n['energy-kcal']||0)),p:Number(n['proteins_100g']||n['proteins']||0),c:Number(n['carbohydrates_100g']||n['carbohydrates']||0),f:Number(n['fat_100g']||n['fat']||0),source:'off',barcode:barcode};console.log('[OFF] Datos mapeados al nuevo formato:',cleanFood);return cleanFood;}catch(error){console.error('[OFF] Error en escaneo:',error);return null;}}
async _loadMasterFoods(){try{const response=await fetch(MASTER_FILE_PATH);if(!response.ok)throw new Error('master_foods.json no encontrado');return await response.json();}catch(e){console.warn('[PANTRY] Fallo al cargar el maestro JSON.',e);return[];}}
async _syncUserDataToDB(){const userData=nutritionStore.getUserData();await db.put(VAULT_NAME,{id:USER_DATA_KEY,data:userData});}
_normalizeText(text){if(!text)return"";return text.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");}}
export const pantryService=new PantryService();