import{db}from'../../../core/db/index.js';import{labStore}from'../store/lab.store.js';import{AI_MODELS}from'../constants.js';import{i18nService}from'../../../core/i18n/i18n.service.js';class LabService{async downloadModel(modelId){const model=AI_MODELS[modelId];if(!model)throw new Error('Modelo no reconocido');const cache=await caches.open('aerko-ai-models-v1');const response=await fetch(model.url);if(!response.ok)throw new Error('Fallo en la descarga del modelo');await cache.put(model.url,response.clone());let config=await db.get('public_store','training_lab_config');if(!config)config={id:'training_lab_config'};config.is_downloaded=true;config.selected_model=modelId;await db.put('public_store',config);console.log(`[LAB SERVICE] Modelo ${model.name} descargado y guardado en caché.`);return true;}
async loadModelBufferFromCache(){const config=await db.get('public_store','training_lab_config');if(!config||!config.selected_model)throw new Error('No hay modelo configurado');const modelUrl=AI_MODELS[config.selected_model].url;const cache=await caches.open('aerko-ai-models-v1');const cachedResponse=await cache.match(modelUrl);if(!cachedResponse)throw new Error('El modelo no está en la caché. Necesita descarga.');console.log(`[LAB SERVICE] Modelo cargado desde la RAM.`);return await cachedResponse.arrayBuffer();}
async analyzeVideo(videoFile,videoElement,onCompleteCallback){console.log('[LAB SERVICE] 🎬 Iniciando análisis biomecánico (Modo Ping-Pong)...');const dict=await i18nService.loadPage('training_lab/lab-service');labStore.setVideoFile(videoFile);const modelBuffer=await this.loadModelBufferFromCache();const targetWidth=480;const targetHeight=640;const offscreen=new OffscreenCanvas(targetWidth,targetHeight);const ctx=offscreen.getContext('2d',{willReadFrequently:true});const worker=new Worker(new URL('../views/pose-worker.js?v='+Date.now(),import.meta.url),{type:'module'});worker.postMessage({type:'INIT',payload:{modelBuffer:modelBuffer}});let lastProcessedTime=-1;let isVideoFinished=false;videoElement.onended=()=>{isVideoFinished=true;};const sendNextFrame=()=>{if(videoElement.ended||isVideoFinished){console.log('[LAB SERVICE] ⏹️ Vídeo terminado. Pidiendo resultados al worker...');worker.postMessage({type:'COMPLETE'});return;}
const currentTimeMs=Math.round(videoElement.currentTime*1000);if(currentTimeMs<=lastProcessedTime){setTimeout(sendNextFrame,33);return;}
lastProcessedTime=currentTimeMs;ctx.drawImage(videoElement,0,0,targetWidth,targetHeight);const imageData=ctx.getImageData(0,0,targetWidth,targetHeight);worker.postMessage({type:'PROCESS_FRAME',payload:{imageData:imageData,timestamp:currentTimeMs}});};worker.onmessage=async(e)=>{const{type,data,error}=e.data;if(type==='READY'){console.log('[LAB SERVICE] 🟢 Worker READY. Preparando vídeo desde el inicio...');videoElement.muted=true;videoElement.currentTime=0;videoElement.play().then(()=>{console.log('[LAB SERVICE] ▶️ Vídeo en marcha. Mandando el primer frame...');sendNextFrame();}).catch(err=>{console.error('[LAB SERVICE] Error reproduciendo:',err);alert(dict.t('alert_play_error'));});}
else if(type==='FRAME_DONE'){sendNextFrame();}
else if(type==='RESULT_FINAL'){console.log(`[LAB SERVICE] 🏁 Análisis completado. Poses detectadas: ${data.length}`);if(data.length===0){alert(dict.t('alert_no_pose'));worker.terminate();const ui=document.querySelector('training-lab-upload');if(ui&&ui.shadowRoot){const vp=ui.shadowRoot.getElementById('view-processing');const vw=ui.shadowRoot.getElementById('view-preview');if(vp&&vw){vp.classList.replace('view-active','hidden');vw.classList.replace('hidden','view-active');}}
return;}
await db.put('public_store',{id:'temp_analysis_data',data:data});labStore.setAnalysisData(data);worker.terminate();console.log('[LAB SERVICE] 🎉 Worker despedido. Cambiando a resultados...');if(onCompleteCallback)onCompleteCallback();}
else if(type==='ERROR'){console.error('[LAB SERVICE] 🚨 ERROR DEL WORKER:',error);worker.terminate();alert(dict.t('alert_analysis_error')+error);const ui=document.querySelector('training-lab-upload');if(ui&&ui.shadowRoot){const vp=ui.shadowRoot.getElementById('view-processing');const vw=ui.shadowRoot.getElementById('view-preview');if(vp&&vw){vp.classList.replace('view-active','hidden');vw.classList.replace('hidden','view-active');}}}};}
startRecording(canvas,videoElement,exerciseName,onCompleteCallback){console.log('[LAB SERVICE] Grabando resultados...');const stream=canvas.captureStream(30);const recorder=new MediaRecorder(stream,{mimeType:'video/webm'});const chunks=[];recorder.ondataavailable=(e)=>chunks.push(e.data);recorder.onstop=()=>{const blob=new Blob(chunks,{type:'video/webm'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.style.display='none';a.href=url;a.download=`Aerko_Analisis_${exerciseName}.webm`;document.body.appendChild(a);a.click();setTimeout(()=>{document.body.removeChild(a);window.URL.revokeObjectURL(url);},100);console.log('[LAB SERVICE] Grabación guardada.');if(onCompleteCallback)onCompleteCallback();};const wasLooping=videoElement.loop;videoElement.loop=false;videoElement.currentTime=0;videoElement.play();recorder.start();videoElement.onended=()=>{recorder.stop();videoElement.onended=null;if(wasLooping){videoElement.loop=true;videoElement.play();}};}}
export const labService=new LabService();