import{unitService}from'../../../core/utils/unit.service.js';const APPLE_MAP={'HKQuantityTypeIdentifierBodyMass':'weight','HKQuantityTypeIdentifierHeight':'height','HKQuantityTypeIdentifierBodyFatPercentage':'bodyFat','HKQuantityTypeIdentifierLeanBodyMass':'muscleMass','HKQuantityTypeIdentifierWaistCircumference':'waist'};const CHUNK_SIZE=1024*1024;class HealthParserService{async parseHealthData(file,sourceId,onProgress=()=>{}){console.log(`%c[HEALTH PARSER] Iniciando extracción de ${sourceId}. Tamaño: ${(file.size / 1024 / 1024).toFixed(2)} MB`,'color: #CCFF00');if(sourceId==='apple_health'){return await this._parseAppleHealthStream(file,onProgress);}else if(sourceId==='google_fit'||sourceId==='samsung_health'){return await this._parseZipData(file,sourceId,onProgress);}else{throw new Error("err_health_unsupported");}}
_parseAppleHealthStream(file,onProgress){return new Promise((resolve,reject)=>{let offset=0;let leftover='';const dailyRecords=new Map();let profileData={gender:null,age:null};const reader=new FileReader();reader.onload=(e)=>{const chunk=leftover+e.target.result;if(!profileData.gender){const meMatch=chunk.match(/<Me([^>]+)>/);if(meMatch){const sex=meMatch[1].match(/HKCharacteristicTypeIdentifierBiologicalSex="([^"]+)"/);const dob=meMatch[1].match(/HKCharacteristicTypeIdentifierDateOfBirth="([^"]+)"/);if(sex)profileData.gender=sex[1].replace('HKBiologicalSex','');if(dob)profileData.age=new Date().getFullYear()-new Date(dob[1]).getFullYear();}}
const recordRegex=/<Record([^>]+)>/g;let match;let lastIndex=0;while((match=recordRegex.exec(chunk))!==null){const attrs=match[1];const typeMatch=attrs.match(/type="([^"]+)"/);if(typeMatch&&APPLE_MAP[typeMatch[1]]){const aerkoKey=APPLE_MAP[typeMatch[1]];const valMatch=attrs.match(/value="([^"]+)"/);const unitMatch=attrs.match(/unit="([^"]+)"/);const dateMatch=attrs.match(/startDate="([^"]+)"/);if(valMatch&&dateMatch){const dayDate=dateMatch[1].split(' ')[0];let val=parseFloat(valMatch[1]);const unit=unitMatch?unitMatch[1].toLowerCase():'';val=unitService.toBase(val,unit.toUpperCase());if(!dailyRecords.has(dayDate)){dailyRecords.set(dayDate,{timestamp:new Date(dayDate).getTime()});}
dailyRecords.get(dayDate)[aerkoKey]=val;}}
lastIndex=match.index+match[0].length;}
leftover=chunk.slice(lastIndex);offset+=CHUNK_SIZE;const progress=Math.min(100,Math.round((offset/file.size)*100));onProgress(progress);if(offset<file.size){readNextChunk();}else{console.log('%c[HEALTH PARSER] Archivo XML de Apple purificado.','color: #CCFF00');resolve({profile:profileData,records:Array.from(dailyRecords.values()).sort((a,b)=>b.timestamp-a.timestamp)});}};reader.onerror=()=>reject(new Error("err_xml_read"));const readNextChunk=()=>{const slice=file.slice(offset,offset+CHUNK_SIZE);reader.readAsText(slice);};readNextChunk();});}
async _parseZipData(file,sourceId,onProgress){const isZip=file.name.toLowerCase().endsWith('.zip')||file.type==='application/zip';const dailyRecords=new Map();if(!isZip){console.log(`%c[HEALTH PARSER] Archivo suelto detectado (${file.name}). Bypass de JSZip.`,'color: orange');const text=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=e=>resolve(e.target.result);reader.onerror=()=>reject(new Error("err_csv_read"));reader.readAsText(file);});const fakeZipEntry={async:async()=>text};let mode='google_weight';if(file.name.toLowerCase().includes('fat')||file.name.toLowerCase().includes('grasa'))mode='google_fat';await this._extractCsvFromZip(fakeZipEntry,dailyRecords,mode);onProgress(100);return{profile:{gender:null,age:null},records:Array.from(dailyRecords.values()).sort((a,b)=>b.timestamp-a.timestamp)};}
if(typeof JSZip==='undefined')throw new Error("err_zip_not_found");const zip=new JSZip();let zipContent;try{zipContent=await zip.loadAsync(file);}catch(e){throw new Error("err_zip_corrupt");}
const filePromises=[];const totalFiles=Object.keys(zipContent.files).length;let filesProcessed=0;zip.forEach((relativePath,zipEntry)=>{if(zipEntry.dir)return;const lowerPath=relativePath.toLowerCase();if(sourceId==='samsung_health'&&lowerPath.includes('com.samsung.health.weight')&&lowerPath.endsWith('.csv')){filePromises.push(this._extractCsvFromZip(zipEntry,dailyRecords,'samsung'));}
if(sourceId==='google_fit'&&lowerPath.endsWith('.csv')){if(lowerPath.includes('weight')||lowerPath.includes('peso')){filePromises.push(this._extractCsvFromZip(zipEntry,dailyRecords,'google_weight'));}
if(lowerPath.includes('body fat')||lowerPath.includes('grasa')){filePromises.push(this._extractCsvFromZip(zipEntry,dailyRecords,'google_fat'));}}
filesProcessed++;if(filesProcessed%10===0){onProgress(Math.min(50,Math.round((filesProcessed/totalFiles)*50)));}});await Promise.all(filePromises);onProgress(100);console.log(`%c[HEALTH PARSER] ZIP de ${sourceId} purificado.`,'color: #CCFF00');return{profile:{gender:null,age:null},records:Array.from(dailyRecords.values()).sort((a,b)=>b.timestamp-a.timestamp)};}
async _extractCsvFromZip(zipEntry,dailyRecords,mode){const content=await zipEntry.async("string");const lines=content.split('\n').map(l=>l.trim()).filter(l=>l);if(lines.length<2)return;let headerIndex=lines.findIndex(l=>l.toLowerCase().includes('weight')||l.toLowerCase().includes('peso')||l.toLowerCase().includes('create_time'));if(headerIndex===-1)headerIndex=0;const headers=lines[headerIndex].toLowerCase().split(',').map(h=>h.replace(/"/g,'').trim());const idxDate=headers.findIndex(h=>h.includes('time')||h.includes('date')||h.includes('fecha'));const idxWeight=headers.findIndex(h=>h.includes('weight')||h.includes('peso')||h==='kg');const idxFat=headers.findIndex(h=>h.includes('fat')||h.includes('grasa'));if(idxDate===-1)return;for(let i=headerIndex+1;i<lines.length;i++){const row=lines[i].split(/,(?=(?:(?:[^"]*"){2})*[^"]*$)/).map(c=>c.replace(/"/g,''));if(row.length<=idxDate)continue;const dateRaw=row[idxDate];const timestamp=new Date(dateRaw).getTime();if(isNaN(timestamp))continue;const dayDate=dateRaw.split(' ')[0];if(!dailyRecords.has(dayDate)){dailyRecords.set(dayDate,{timestamp});}
const record=dailyRecords.get(dayDate);if(timestamp>=record.timestamp){record.timestamp=timestamp;if(idxWeight!==-1&&row[idxWeight]){const w=parseFloat(row[idxWeight]);if(!isNaN(w))record.weight=unitService.toBase(w,'KG');}
if(idxFat!==-1&&row[idxFat]){const f=parseFloat(row[idxFat]);if(!isNaN(f))record.bodyFat=unitService.toBase(f,'%');}}}}}
export const healthParserService=new HealthParserService();