import{db}from'../../../core/db/index.js';import{cryptoService}from'../../../core/crypto/index.js';const STORE='public_store';const CONFIG_ID='app_config';const CANARY_ID='auth_canary';const SALT_ID='auth_salt';class AuthService{async hasPin(){const config=await this._getConfig();return!!config.security_enabled;}
isSessionActive(){return!!cryptoService.key;}
async isOnboardingComplete(){const config=await this._getConfig();return!!config.onboarding_complete;}
async completeOnboarding(){const config=await this._getConfig();config.onboarding_complete=true;await db.put(STORE,config);}
async verifyPin(pin){const saltRecord=await db.get(STORE,SALT_ID);if(!saltRecord){console.error('[AUTH] No salt found. Critical integrity error.');return false;}
const keyGenerated=await cryptoService.initSession(pin,saltRecord.value);if(!keyGenerated)return false;try{const canary=await db.get(STORE,CANARY_ID);if(!canary){console.warn('[AUTH] Security flag is ON but Canary is missing.');return true;}
const decrypted=await cryptoService.decrypt(canary.data);return decrypted.secret==='AERKO_SECURE';}catch(error){console.error('[AUTH] PIN Incorrecto (Fallo al descifrar canario).');return false;}}
async enableSecurity(pin){const saltArray=window.crypto.getRandomValues(new Uint8Array(16));const saltHex=Array.from(saltArray).map(b=>b.toString(16).padStart(2,'0')).join('');console.log('[AUTH] Generating unique salt for user:',saltHex);await db.put(STORE,{id:SALT_ID,value:saltHex});await cryptoService.initSession(pin,saltHex);const canaryPayload={secret:'AERKO_SECURE',timestamp:Date.now()};const encryptedCanary=await cryptoService.encrypt(canaryPayload);await db.put(STORE,{id:CANARY_ID,data:encryptedCanary});const config=await this._getConfig();config.security_enabled=true;await db.put(STORE,config);console.log('[AUTH] Iniciando migración a datos cifrados...');for(const vault of config.protected_vaults){const records=await db._transaction(vault,'readonly',store=>store.getAll());for(const record of records){await db.put(vault,record);}}
console.log('[AUTH] Security Enabled with Unique Salt & Data Migrated.');}
async updateProtectedVaults(vaultsArray){const config=await this._getConfig();config.protected_vaults=vaultsArray;await db.put(STORE,config);console.log('[AUTH] Bóvedas protegidas actualizadas:',vaultsArray);}
async disableSecurity(currentPin){const isValid=await this.verifyPin(currentPin);if(!isValid)return false;const config=await this._getConfig();console.log('[AUTH] Iniciando reversión a datos en texto plano...');for(const vault of config.protected_vaults){const records=await db._transaction(vault,'readonly',store=>store.getAll());for(const record of records){if(record.data&&record.data.iv){const decryptedPayload=await cryptoService.decrypt(record.data);const plainRecord={id:record.id,...decryptedPayload};await db._transaction(vault,'readwrite',store=>store.put(plainRecord));}}}
console.log('[AUTH] Reversión a texto plano completada.');await db.delete(STORE,CANARY_ID);await db.delete(STORE,SALT_ID);config.security_enabled=false;await db.put(STORE,config);cryptoService.lock();console.log('[AUTH] Security Disabled. Keys destroyed.');return true;}
async _getConfig(){const config=await db.get(STORE,CONFIG_ID);if(!config){return{id:CONFIG_ID,security_enabled:false,onboarding_complete:false,protected_vaults:['user_vault','nutrition_vault','training_vault','progress_vault']};}
if(!config.protected_vaults){config.protected_vaults=['user_vault','nutrition_vault','training_vault','progress_vault'];}
return config;}}
export const authService=new AuthService();