import{db}from'../../../core/db/index.js';import{trainingStore}from'../store/index.js';const VAULT_NAME='training_vault';const SESSIONS_KEY='training_sessions';const EXERCISES_KEY='master_exercises';class AnalysisService{getTargetRIR(currentWeek,totalWeeks){if(currentWeek===1)return 3;if(currentWeek>=totalWeeks)return 4;if(currentWeek===totalWeeks-1)return 0;const weeksToProgress=(totalWeeks-1)-1;const rirDropPerWeek=3/weeksToProgress;const rawRir=3-(rirDropPerWeek*(currentWeek-1));return Math.round(rawRir*10)/10;}
async _getLastSessionSets(exerciseId){const record=await db.get(VAULT_NAME,SESSIONS_KEY);if(!record||!record.data||record.data.length===0)return null;const sessions=record.data;for(let i=sessions.length-1;i>=0;i--){const session=sessions[i];const exercise=session.exercises.find(ex=>ex.id===exerciseId);if(exercise&&exercise.sets&&exercise.sets.length>0){return exercise.sets;}}
return null;}
_extractEffectiveSets(sets){let topSetIndex=0;let maxE1RM=0;sets.forEach((set,index)=>{const rirToUse=set.rir!==null?set.rir:0;const e1RM=set.kg*(1+((set.reps+rirToUse)/30));if(e1RM>maxE1RM){maxE1RM=e1RM;topSetIndex=index;}});const topSet=sets[topSetIndex];const effectiveSets=sets.filter((set,index)=>{if(index<topSetIndex&&set.kg<(topSet.kg*0.65)){return false;}
return true;});return{topSet,effectiveSets};}
_roundWeight(weight){return Math.round(weight/2.5)*2.5;}
async generateSuggestion(exerciseId,currentWeek,totalWeeks){console.log(`%c[ANALYSIS ENGINE] Booting prediction for Exercise: ${exerciseId}...`,'color: #CCFF00');const pastSets=await this._getLastSessionSets(exerciseId);if(!pastSets){console.log('[ANALYSIS ENGINE] No history found. Manual input required.');return null;}
const{topSet,effectiveSets}=this._extractEffectiveSets(pastSets);const targetRIR=this.getTargetRIR(currentWeek,totalWeeks);if(targetRIR===4){console.log('%c[ANALYSIS ENGINE] Deload Protocol Activated. Cutting volume & intensity.','color: #00bcd4');const deloadSets=[];const numSets=Math.max(1,effectiveSets.length-1);for(let i=0;i<numSets;i++){const oldSet=effectiveSets[i];deloadSets.push({kg:this._roundWeight(oldSet.kg*0.90),reps:oldSet.reps,rir:4});}
return deloadSets;}
const oldRir=topSet.rir!==null?topSet.rir:2;const rirDiff=oldRir-targetRIR;let newTopKg=this._roundWeight(topSet.kg*(1+(rirDiff*0.025)));let newTopReps=topSet.reps;const meso=trainingStore.state.mesocycle;const focus=meso?meso.focus.toLowerCase():'general';const virtual1RM=newTopKg*(1+(newTopReps/30));if(focus==='fuerza'&&newTopReps>5){console.log('[ANALYSIS ENGINE] Focus: Fuerza. Transmutando repes a rango pesado (4).');newTopReps=4;newTopKg=this._roundWeight(virtual1RM/(1+(newTopReps/30)));}
else if(focus==='hipertrofia'&&(newTopReps<8||newTopReps>12)){console.log('[ANALYSIS ENGINE] Focus: Hipertrofia. Transmutando repes a rango óptimo (10).');newTopReps=10;newTopKg=this._roundWeight(virtual1RM/(1+(newTopReps/30)));}
else if(focus==='resistencia'&&newTopReps<15){console.log('[ANALYSIS ENGINE] Focus: Resistencia. Transmutando repes a rango alto (15).');newTopReps=15;newTopKg=this._roundWeight(virtual1RM/(1+(newTopReps/30)));}
const suggestedSets=[];effectiveSets.forEach((oldSet)=>{if(oldSet===topSet){suggestedSets.push({kg:newTopKg,reps:newTopReps,rir:targetRIR});return;}
if(oldSet.kg===topSet.kg){const repsRatio=oldSet.reps/topSet.reps;suggestedSets.push({kg:newTopKg,reps:Math.max(1,Math.round(newTopReps*repsRatio)),rir:targetRIR});}else{const kgRatio=oldSet.kg/topSet.kg;suggestedSets.push({kg:this._roundWeight(newTopKg*kgRatio),reps:oldSet.reps,rir:targetRIR});}});console.log('[ANALYSIS ENGINE] Prediction successful:',suggestedSets);return suggestedSets;}
async calculateWeeklyVolume(startDate,endDate){console.log(`%c[ANALYSIS ENGINE] Calculating Volume from ${new Date(startDate).toLocaleDateString()} to ${new Date(endDate).toLocaleDateString()}`,'color: #CCFF00');const sessionsRecord=await db.get(VAULT_NAME,SESSIONS_KEY);if(!sessionsRecord||!sessionsRecord.data)return null;const validSessions=sessionsRecord.data.filter(session=>session.timestamp>=startDate&&session.timestamp<=endDate);if(validSessions.length===0)return null;const masterExercisesRecord=await db.get(VAULT_NAME,EXERCISES_KEY);const masterExercises=masterExercisesRecord&&masterExercisesRecord.data?masterExercisesRecord.data:[];let musclesData=[];try{const response=await fetch('/src/assets/data/muscles.json');musclesData=await response.json();}catch(error){console.error('[ANALYSIS ENGINE] Error loading muscles.json',error);return null;}
const volumeTracker={};validSessions.forEach(session=>{session.exercises.forEach(ex=>{const masterEx=masterExercises.find(m=>m.id===ex.id);if(!masterEx||!masterEx.impact||!masterEx.impact.activation)return;const{effectiveSets}=this._extractEffectiveSets(ex.sets);const validSetCount=effectiveSets.length;if(validSetCount===0)return;const activations=masterEx.impact.activation;const targetMuscles=masterEx.impact.targets||[];targetMuscles.forEach(muscleId=>{if(!volumeTracker[muscleId]){volumeTracker[muscleId]={total_volume:0,heads:{}};}
const maxActivation=Math.max(...Object.values(activations));volumeTracker[muscleId].total_volume+=(validSetCount*maxActivation);Object.entries(activations).forEach(([headId,coefficient])=>{if(!volumeTracker[muscleId].heads[headId]){volumeTracker[muscleId].heads[headId]=0;}
volumeTracker[muscleId].heads[headId]+=(validSetCount*coefficient);});});});});const finalReport={alerts:[],optimal:[]};const TOLERANCE=0.15;Object.entries(volumeTracker).forEach(([muscleId,data])=>{const muscleDef=musclesData.find(m=>m.id===muscleId);if(!muscleDef)return;const totalVol=data.total_volume;let status='GREY';const limits=muscleDef.weekly_limits;let isOverload=false;if(totalVol>=limits.mv&&totalVol<limits.mav)status='LIGHT_GREEN';if(totalVol>=limits.mav&&totalVol<=limits.mrv)status='ACID_GREEN';if(totalVol>limits.mrv){status='RED';isOverload=true;}
let headAlerts=[];let totalHeadVolume=0;Object.values(data.heads).forEach(v=>totalHeadVolume+=v);if(totalHeadVolume>0&&muscleDef.heads&&muscleDef.heads.length>0){muscleDef.heads.forEach(headDef=>{const realVolume=data.heads[headDef.id]||0;const realRatio=realVolume/totalHeadVolume;const idealRatio=headDef.ideal_ratio||0;if((idealRatio-realRatio)>TOLERANCE){headAlerts.push({type:'under',name:headDef.name.es,real:Math.round(realRatio*100),ideal:Math.round(idealRatio*100)});}else if((realRatio-idealRatio)>TOLERANCE){headAlerts.push({type:'over',name:headDef.name.es,real:Math.round(realRatio*100),ideal:Math.round(idealRatio*100)});}});}
const resultObj={muscleId:muscleId,muscleName:muscleDef.name.es,volume:Math.round(totalVol*10)/10,status:status,headAlerts:headAlerts};if(isOverload||headAlerts.length>0){finalReport.alerts.push(resultObj);}else{finalReport.optimal.push(resultObj);}});console.log('[ANALYSIS ENGINE] Weekly Volume Report generated:',finalReport);return finalReport;}}
export const analysisService=new AnalysisService();