import{db}from'../../../core/db/index.js';import{trainingStore}from'../store/index.js';const VAULT_NAME='training_vault';const SESSIONS_KEY='training_sessions';const SNAPSHOT_KEY='exercise_snapshot';class SessionService{async startSession(routineId){console.log(`[SESSION] Warming up for routine: ${routineId}`);const routine=trainingStore.getRoutineById(routineId);if(!routine)throw new Error("Rutina no encontrada en RAM");let snapshot=trainingStore.getSnapshot();if(Object.keys(snapshot).length===0){const record=await db.get(VAULT_NAME,SNAPSHOT_KEY);snapshot=record?record.data:{};trainingStore.setSnapshot(snapshot);}
const hydratedExercises=routine.exercises.map(simpleEx=>{const masterEx=trainingStore.getExerciseById(simpleEx.id);return{id:simpleEx.id,name:masterEx?(masterEx.name.es||masterEx.name):null,nameKey:masterEx?null:"core_fallback_exercise",target:masterEx?masterEx.impact:{},sets:[]};});const newSession={id:crypto.randomUUID(),routineId:routineId,routineName:routine.name,startTime:Date.now(),exercises:hydratedExercises,status:'active'};trainingStore.startSession(newSession);console.log('[SESSION] Whistle blown! Match started.',newSession);return newSession;}
logSet(exerciseId,kg,reps,rir){const session=trainingStore.getActiveSession();if(!session){console.error("No hay sesión activa");return;}
const set={kg:parseFloat(kg),reps:parseInt(reps),rir:parseInt(rir),timestamp:Date.now()};trainingStore.addSetToSession(exerciseId,set);const e1RM=set.kg*(1+(0.0333*set.reps));const previousBest=trainingStore.getExerciseSnapshot(exerciseId);let isRecord=false;if(previousBest){const prevE1RM=previousBest.lastKg*(1+(0.0333*previousBest.lastReps));if(e1RM>prevE1RM)isRecord=true;}else{isRecord=true;}
if(isRecord){console.log(`%c[SESSION] 🏆 NEW RECORD! e1RM: ${e1RM.toFixed(1)}kg`,'color: #CCFF00');}}
async finishSession(){const session=trainingStore.getActiveSession();if(!session)return;session.endTime=Date.now();session.duration=Math.floor((session.endTime-session.startTime)/1000);session.status='completed';console.log('[SESSION] Final whistle. Processing stats...');try{const historyRecord=await db.get(VAULT_NAME,SESSIONS_KEY);const history=historyRecord?historyRecord.data:[];const cleanSession={id:session.id,timestamp:session.endTime,routineId:session.routineId,duration:session.duration,exercises:session.exercises.map(ex=>({id:ex.id,sets:ex.sets})).filter(ex=>ex.sets.length>0)};history.push(cleanSession);await db.put(VAULT_NAME,{id:SESSIONS_KEY,data:history});const currentSnapshot=trainingStore.getSnapshot();let snapshotUpdated=false;session.exercises.forEach(ex=>{if(ex.sets.length===0)return;let bestSetToday=null;let maxE1RM=0;ex.sets.forEach(set=>{const val=set.kg*(1+(0.0333*set.reps));if(val>maxE1RM){maxE1RM=val;bestSetToday=set;}});const prevStats=currentSnapshot[ex.id];let isNewRecord=false;if(!prevStats){isNewRecord=true;}else{const prevMax=prevStats.lastKg*(1+(0.0333*prevStats.lastReps));if(maxE1RM>prevMax)isNewRecord=true;}
if(isNewRecord&&bestSetToday){currentSnapshot[ex.id]={lastKg:bestSetToday.kg,lastReps:bestSetToday.reps,lastRir:bestSetToday.rir,timestamp:Date.now()};snapshotUpdated=true;}});if(snapshotUpdated){await db.put(VAULT_NAME,{id:SNAPSHOT_KEY,data:currentSnapshot});trainingStore.setSnapshot(currentSnapshot);}
trainingStore.clearSession();console.log('[SESSION] Stats saved. Shower time.');return true;}catch(error){console.error('[SESSION] Critical Error saving session:',error);throw error;}}
cancelSession(){trainingStore.clearSession();console.log('[SESSION] Match cancelled.');}}
export const sessionService=new SessionService();